{ config
, lib
, pkgs
, android-nixpkgs
, mainUser
, ...
}:

{
  imports = [
    ../../modules/home/common-packages.nix
    ../../modules/home/gtk-qt.nix
    ../../modules/home/neovim
    ../../modules/home/nixos-common-pkgs.nix
    ../../modules/home/version-control.nix
    ../../modules/nixos/foot.nix
    ../../modules/nixos_and_darwin/alacritty.nix

    android-nixpkgs.hmModule
  ];

  debling.editors.neovim.enable = true;

  debling.alacritty.enable = true;

  news.display = "show";

  home = {
    enableNixpkgsReleaseCheck = true;

    packages = with pkgs; [
      kmonad

      anydesk

      babashka
      gh

      gnumake
      snitch
      maven

      ### Editors/IDEs
      # jetbrains.datagrip
      # jetbrains.idea-ultimate
      visualvm

      ### Langs related
      # idris2 # A language with dependent types, XXX: compilation is broken on m1 for now https://github.com/NixOS/nixpkgs/issues/151223
      # ansible
      clojure # Lisp language with sane concurrency
      nodejs
      nodePackages.pnpm
      pipenv


      (python313.withPackages (
        ps: with ps; [
          pandas
          numpy
          ipython
          matplotlib
          seaborn
          # jupyterlab
          pudb
          # torch
          pyarrow
          boto3
          scikit-learn
        ]
      ))
      # poetry

      # unrar
      postgresql_15

      taskwarrior-tui
      timewarrior

      # vagrant
      ouch # Painless compression and decompression for your terminal https://github.com/ouch-org/ouch
      # https://github.com/mic92/nix-update
      # nix-init # https://github.com/nix-community/nix-init
      oha # HTTP load generator https://github.com/hatoo/oha

      trivy
      cht-sh # https://github.com/chubin/cheat.sh
      # nix-du

      # https://magic-wormhole.readthedocs.io/en/latest/welcome.html#example
      # magic-wormhole # Send files over the network

      glow
    ];
  };

  xdg.configFile = {
    snitch = {
      source = ../../config/snitch;
      recursive = true;
    };
  };

  systemd.user.startServices = "sd-switch";

  ####
  #### The section bellow is auto-generated by home-manager
  ####

  # Home Manager needs a bit of information about you and the
  # paths it should manage.
  home.username = mainUser;
  home.homeDirectory = "/home/debling";

  # This value determines the Home Manager release that your
  # configuration is compatible with. This helps avoid breakage
  # when a new Home Manager release introduces backwards
  # incompatible changes.
  #
  # You can update Home Manager without changing this value. See
  # the Home Manager release notes for a list of state version
  # changes in each release.
  home.stateVersion = "22.05";

  # Let Home Manager install and manage itself.
  programs.home-manager.enable = true;
}
