#!/bin/sh


apk=$1
pkg=$(aapt dump badging "$apk" |awk -F" " '/package/ {print $2}' | awk -F"'" '/name=/ {print $2}')
act=$(aapt dump badging "$apk" |awk -F" " '/launchable-activity/ {print $2}' | awk -F"'" '/name=/ {print $2}')

adb install -r -t "$apk"
adb shell am start -n "${pkg}/${act}"

app_pid=$(adb shell ps | grep "$pkg"  | tr -s '[:space:]' ' ' | cut -d' ' -f2)
adb logcat --pid="$app_pid"
