#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/Workspace/* -mindepth 1 -maxdepth 1 -type d | fuzzel --dmenu)
fi

if [[ -z $selected ]]; then
    exit 0
fi

cd "$selected" && exec fish
